BrandBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.BrandBucket.name}
    LifecycleConfiguration:
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 1

BrandBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: ${self:custom.BrandBucket.name} 
    PolicyDocument:
      Statement:
        - Sid: PublicRead
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.BrandBucket.name}/*